//
//  PathKit.swift
//  PathKit
//
//  Created by Rajan on Nov 21, 2019.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class PathKit: NSObject {
    
    
    //MARK: - Canvas Drawings
    
    /// Page 1
    
    class func drawPage1() {
        /// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        /// Path
        let path = UIBezierPath()
        path.move(to: CGPoint.zero)
        path.addLine(to: CGPoint(x: 201.13, y: 0))
        path.addLine(to: CGPoint(x: 201.13, y: 162.88))
        context.saveGState()
        context.translateBy(x: 273.67, y: 229.1)
        path.setLineDash([10], count: 1, phase: 0)
        path.lineWidth = 1
        UIColor(white: 0.592, alpha: 1).setStroke()
        path.stroke()
        context.restoreGState()
    }
    
    
}
